version: 0.2

env:
  variables:
    DOCKER_IMAGE: artifactory.dowjones.io:5003/djis/pnp-billing-config/service-api
  secrets-manager:
    DOCKER_USERNAME: cerebro/artifactory-docker:username
    DOCKER_PASSWORD: cerebro/artifactory-docker:password
    NPM_USERNAME: cerebro/artifactory-npm-ro:username
    NPM_PASSWORD: cerebro/artifactory-npm-ro:password

phases:
  pre_build:
    commands:
      - echo Logging in to Artifactory
      - aws --version
      - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin https://artifactory.dowjones.io:5003
      - echo Configuring NPM...
      - npm config set _auth $(echo -n ${NPM_USERNAME}:${NPM_PASSWORD} | base64 --wrap 0)
      - npm config set registry https://artifactory.dowjones.io/artifactory/api/npm/djis-npm-virtual
      - npm config set always-auth true
      - npm config set email smpdevops@dowjones.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} --build-arg build_number=${BUILD_NUMBER} <path-to-dockerfile>
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging latest image
      - echo Pushing the Docker images...
      - docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}