version: '3.9'

services:
  api:
    container_name: pnp-api
    image: pnp-billing-config-api:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: node run start:debug-pnp
    env_file: .env
    ports:
      - '5002:5002'
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database
  database:
    container_name: mysql2
    image: mysql/mysql-server
    env_file: .env
    networks:
      - app-network
    ports:
      - '3306:3306'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  app-network:
